### ISSUE TITLE
As a user, I should be able to view route directions in the app, on my mobile device.

### ISSUE THREAD

**Issue by jasonsreynolds** [freeCodeCamp/food-bank-app#10]

**Comment by Rusticman** [comment]
Hey, I'd like to tackle this one. Could you please provide further information on what you specifically want.

**Comment by DealPete** [comment]
Right now when you log in as a driver you get a route assignment with address, but no directions (and the mobile interface could use improvement as well). Having google maps integrated, with the route appearing automatically, would be very convenient for the driver. A button that opened the Google Maps app on android and sent it the route would be another way to do this. I'm not sure which solution is easier to implement from a technical standpoint.

**Comment by Rusticman** [comment]
Ok, great. When I've finished with the new map implementation, I'll have a look at this.

**Comment by Rusticman** [comment]
Hi Pete, I'm getting this error message in a few different instances:

```ReferenceError: _ is not defined```

It happens when I'm signed in as admin @
1. "volunteer database" tab when I click "edit" and "view".
2. "client database tab" when I click on "edit" and "view".

When I sign in as a volunteer it also happens. I just wanted to know if you also get this error message or is it a problem my end? Seems like it might be a case of injecting it into the controller .

 Also, you mention that the volunteer (driver) should receive the addresses of the food parcel recipients, but I haven't been able to trigger that. I'm not sure if this is directly correlated to the above or if this is simply an error in my own use of the app.

I've added clients & volunteers and accepted their applications. I've assigned volunteers to clients, created an inventory and food schedule. Pressed the "send packages" button in packing list tab. Every time I sign in as a volunteer, there is only an "edit application" tab in the sidebar, in the main window is my name, an "accept" button and "cancel" button. 

I did a pull request on the FCC staging branch today so I'm up-to-date.

**Comment by MAF27** [comment]
Hi Russell

I pushed a largish cleanup commit for dynamic forms and the roles issue yesterday, works fine on my end. The symbol _ is used for lodash, is that installed on your end? If that's missing, it might explain some of the issues you're seeing.

**Comment by Rusticman** [comment]
Hi Marco,

I've installed the lodash package, version 4.17.2, and I'm still seeing these errors in the console. Not sure what it could be.  Pretty strange if it works on your end and not mine.

**Comment by DealPete** [comment]
Hi Russell,

Like Russell said, the _ is for lodash, so there must be a problem with that dependency. Have you tried deleting your node_modules directory and reinstalling? That sometimes does the trick for me. The files that use lodash will have a "_ = require('lodash') statement near the top. You could check the file that is throwing an error to verify that it has that statement.

With respect to the other issue, there should be a "route assignment" menu tap appearing in the sidebar. Are you sure that you're logging in with a volunteer that has been designated as a "driver" by an admin? I do see the "route assignment" menu appear on the sidebar, but I am getting some errors. It worked for me in the past; it's possible that an update has damaged this part of the code. It'll be your job to figure out what went wrong.

**Comment by Rusticman** [comment]
Yep, I deleted my node_modules folder and re-installed the npm dependencies but it's still the same.  The errors aren't coming from the server-side lodash, but from the client-side lodash within the controllers.  I noticed that the lodash script isn't being loaded at compile time which is why it is undefined. It isn't attaching to the window object. 

I designated every volunteer a driver so far, I have a feeling that it is something to do with the errors in the controllers that are stopping it. 

Could you confirm that you're receiving the same error? Or are they different? On Friday, I was seeing different errors which have disappeared now. I'm only seeing this one:

```ReferenceError: _ is not defined```

I'm happy to look into it and figure out what is happening.

**Comment by MAF27** [comment]
If it's on the client side, it might help to delete public/lib completely and reinstall all bower dependencies.

**Comment by Rusticman** [comment]
I deleted the node_modules directory and all the files in the public/lib directory and reinstalled without much luck. Forgive my inexperience using bower, I haven't used it before.  

I noticed that the lodash component  isn't actually in the public/lib directory. This is why it's not loading at compile time in the config/env/all.js file. The reference is ---> 'public/lib/lodash/dist/lodash.min.js'. 

From what I understand, bower should be used client-side and npm should be used server-side (as a rule of thumb, not strictly true). Lodash doesn't support bower anymore which is why it's in the package.json file. What I'm struggling to understand is, how does node (npm) push the lodash component to the public/lib file (bower)?

I hope that makes sense.

**Comment by Rusticman** [comment]
I put this line: 
```"lodash": "~4.17.4",```
 into the bower.json file for client-side use and it works perfectly. It now loads during compiling and it appears in the elements tab of the console with all the other scripts. I'm still a bit confused how it works otherwise.  In news that pertains to this issue, I have the route assignment tab appearing in the sidebar when signed in as a volunteer. There are indeed errors to be resolved so I'll get on that now 👍

**Comment by DealPete** [comment]
okay, I figured it out. `lodash` was being installed as part of `angular-google-maps`. When we removed that from `bower.json` it broke the app. I've added lodash back, so if you pull in the latest staging it should work.

**Comment by Rusticman** [comment]
good catch, Pete. I would never have checked that package.  Good to know going forward
